run-name: Deploy Terraform Structure Workflow
name: Deploy Terraform Structure Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy_terraform_structure:
    name: Deploy Terraform Structure
    runs-on: ubuntu-24.04

    env:
      TF_VAR_AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_VAR_AWS_REGION:             ${{ secrets.AWS_REGION }}
      TF_VAR_AWS_ZONE_1:             ${{ secrets.AWS_ZONE_1 }}
      TF_VAR_AWS_ZONE_2:             ${{ secrets.AWS_ZONE_2 }}

      TF_VAR_VPC_IP:                 ${{ secrets.VPC_IP }}
      TF_VAR_VPC_SUBNET1_IP:         ${{ secrets.VPC_SUBNET1_IP }}
      TF_VAR_VPC_SUBNET2_IP:         ${{ secrets.VPC_SUBNET2_IP }}

      TF_VAR_APP_VERSION:            ${{ secrets.APP_VERSION }}

      TF_VAR_EC2_AMI_ID:             ${{ secrets.EC2_AMI_ID }}
      TF_VAR_EC2_INSTANCE_TYPE:      ${{ secrets.EC2_INSTANCE_TYPE }}

    steps:
      - name: Checkout Out Repository Code / Create Project Repository Clone
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.12.1

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             ${{ secrets.AWS_REGION }}

      - name: Cloud Init AWS
        run: make cloud-init-aws

      - name: Cloud Start AWS
        run: make github-actions-cloud-start-aws


  destroy_terraform_structure:
    name: Destroy Terraform Structure
    needs: deploy_terraform_structure
    runs-on: ubuntu-24.04

    env:
      TF_VAR_AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_VAR_AWS_REGION:             ${{ secrets.AWS_REGION }}
      TF_VAR_AWS_ZONE_1:             ${{ secrets.AWS_ZONE_1 }}
      TF_VAR_AWS_ZONE_2:             ${{ secrets.AWS_ZONE_2 }}

      TF_VAR_VPC_IP:                 ${{ secrets.VPC_IP }}
      TF_VAR_VPC_SUBNET1_IP:         ${{ secrets.VPC_SUBNET1_IP }}
      TF_VAR_VPC_SUBNET2_IP:         ${{ secrets.VPC_SUBNET2_IP }}

      TF_VAR_APP_VERSION:            ${{ secrets.APP_VERSION }}

      TF_VAR_EC2_AMI_ID:             ${{ secrets.EC2_AMI_ID }}
      TF_VAR_EC2_INSTANCE_TYPE:      ${{ secrets.EC2_INSTANCE_TYPE }}

    steps:
      - name: Wait Before Destroy (10min)
        run: sleep 600

      - name: Checkout Out Repository Code / Create Project Repository Clone
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.12.1

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             ${{ secrets.AWS_REGION }}

      - name: Cloud Init AWS
        run: make cloud-init-aws

      - name: Cloud Finish AWS
        run: make github-actions-cloud-finish-aws
